use std::str::FromStr;
use std::rc::Rc;
use lalrpop_util::ErrorRecovery;
use crate::compilation_unit::CompilationUnit;
use crate::compilation_unit::Location;

grammar<'err, 'cu>(errors: &'err mut Vec<ErrorRecovery<usize, Token<'input>, &'static str>>, compilation_unit: &'cu Rc<CompilationUnit>);

pub Term: i32 = {
    <n:Number> => n,
};

Number: i32 = <s:r"[0-9]+"> => i32::from_str(s).unwrap();